### ISSUE TITLE
systemd unit file and archlinux package

### ISSUE THREAD

**Issue by schnili** [arnarg/waybind#1]
Hi, thank you for making this!

In the blog post you mentioned the systemd unit. Would it be possible to add it to the repo (like the one in @czaplicki [fork](https://github.com/czaplicki/waybind) but without the install files) ?

I also made a [AUR package](https://aur.archlinux.org/packages/waybind-git/)  for archlinux. If you want to i could make a pr with it added to the README or something :)

**Comment by arnarg** [comment]
I looked at your AUR PKGBUILD and I see you're installing it in `/usr/bin` so I just made the systemd service file with that path. You'll need to create the `waybind` user and group as well as the `uinput` group like is done in the install files in @czaplicki's fork.

Thanks for making the AUR package, I'll accept the PR.
